//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assignment2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to topAdmin,ImTheBest,Tony,Stark,SuperAdmin,10,1.25
        ///SecondAdmin,HesNotTheBest,Kara,Danvers,Moderator,11,3.8
        ///1Admin,2shakeAndFries2,Ronald,McDonald,SuperAdmin,4,4
        ///thatPerson,noTh4nk5,Kate,Middleton,Moderator,0,0.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user1,password123,John,Smith,12-09-1973,7,4.2
        ///user2,321password,Diana,Prince,29-01-1986,3,5
        ///jimmy,123456,Jim,Bean,07-11-1982,2,3.82
        ///NotBatman,UTS2017,Bruce,Wayne,24-02-2007,3,0.
        /// </summary>
        internal static string Guests {
            get {
                return ResourceManager.GetString("Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to topAdmin,ImTheBest,Tony,Stark,10,1.25
        ///SecondAdmin,HesNotTheBest,Kara,Danvers,11,3.79999995231628
        ///1Admin,2shakeAndFries2,Ronald,McDonald,4,4
        ///thatPerson,noTh4nk5,Kate,Middleton,0,0
        ///.
        /// </summary>
        internal static string testAdmin {
            get {
                return ResourceManager.GetString("testAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user1,password123,John,Smith,7,12-09-1973
        ///user2,321password,Diana,Prince,3,29-01-1986
        ///jimmy,123456,Jim,Bean,2,07-11-1982
        ///NotBatman,UTS2017,Bruce,Wayne,3,24-02-2007
        ///.
        /// </summary>
        internal static string testGuest {
            get {
                return ResourceManager.GetString("testGuest", resourceCulture);
            }
        }
    }
}
